#!/usr/bin/env python3
"""Generate the "At a Glance" digest + per-paper TL;DR for the papers index.

The paper *data model* is the set of `.paper-card` blocks already present in
`index.html` (the canonical listing). Each card carries a `.glance` highlight
list and a descriptive summary paragraph. This script rolls those up into a
single presentation block, injected at the top of the papers section:

  1. "At a Glance"   - the top highlight from every paper, one digest list
                       (prefers the NEW-flagged highlight per paper).
  2. "Per-paper TL;DR" - a one-line summary per paper, derived from the first
                       sentence of its summary paragraph (falling back to its
                       top highlight when the summary is empty or too short).

The block lives between HTML marker comments so it is regenerated in place and
never hand-edited. Pure Python standard library, deterministic and offline, so
it fits the existing `scripts/check_*.py` CI model.

Usage:
  python3 scripts/highlights.py           # regenerate + write index.html
  python3 scripts/highlights.py --check    # verify no drift (CI gate; exit 1)

HARD RULE: this generator never emits em (U+2014) or en (U+2013) dashes; any
that appear in source text are normalised to commas / hyphens on the way out.
"""
import argparse
import html
import os
import re
import sys
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")

TOP_N = 6            # max cross-paper highlights in the digest
TLDR_MAX_LEN = 200   # per-paper TL;DR is truncated past this many chars

MARK_START = "<!-- AT-A-GLANCE:START (generated by scripts/highlights.py) -->"
MARK_END = "<!-- AT-A-GLANCE:END -->"
CSS_MARK = "/* AT-A-GLANCE-CSS (scripts/highlights.py) */"

_EM = chr(0x2014)  # em dash (defined via chr so this file stays literally dash-free)
_EN = chr(0x2013)  # en dash


# ---------------------------------------------------------------------------
# text helpers
# ---------------------------------------------------------------------------

def sanitize_dashes(text):
    """Remove em/en dashes: spaced dashes become a comma, bare ones a hyphen.

    A spaced dash ( ` X ` ) reads as a clause break, so a comma preserves the
    grammar; a bare dash between tokens is a connector, so a plain hyphen fits.
    Guarantees the output contains no U+2014 / U+2013.
    """
    text = re.sub(r"\s*[%s%s]\s+" % (_EM, _EN), ", ", text)  # spaced -> comma
    text = re.sub(r"[%s%s]" % (_EM, _EN), "-", text)          # bare -> hyphen
    return re.sub(r"\s{2,}", " ", text).strip()


def first_sentence(text):
    """First sentence: up to the first period followed by whitespace.

    A period with no trailing space (version ids like ``v1.0.0`` or ``3.6``)
    does not split, so decimals and dotted names stay intact.
    """
    text = text.strip()
    m = re.search(r"\.\s", text)
    return (text[: m.start() + 1] if m else text).strip()


def truncate(text, limit=TLDR_MAX_LEN):
    if len(text) <= limit:
        return text
    cut = text[: limit - 3].rstrip()
    sp = cut.rfind(" ")
    if sp > 0:
        cut = cut[:sp]
    return cut.rstrip(".,;: ") + "..."


# ---------------------------------------------------------------------------
# feature functions (operate on the plain paper data model)
# ---------------------------------------------------------------------------

def derive_tldr(paper):
    """One-line TL;DR for a paper.

    Prefers the first sentence of the summary paragraph. When that is empty or
    too short to stand alone, falls back to the paper's top highlight.
    """
    summary = (paper.get("summary") or "").strip()
    candidate = first_sentence(summary)
    if len(candidate) < 25:  # empty / short-abstract edge case
        highs = paper.get("highlights") or []
        if highs:
            candidate = first_sentence(highs[0]["text"]) or highs[0]["text"].strip()
    if not candidate:
        return ""
    return truncate(sanitize_dashes(candidate))


def _top_highlight(paper):
    highs = paper.get("highlights") or []
    if not highs:
        return None
    for h in highs:
        if h.get("is_new"):
            return h
    return highs[0]


def at_a_glance(papers, top_n=TOP_N):
    """Cross-paper rollup: the single top highlight from each paper, top-N.

    Papers keep document order; the NEW-flagged highlight wins within a paper;
    papers with no highlights are skipped.
    """
    picks = []
    for p in papers:
        top = _top_highlight(p)
        if not top:
            continue
        picks.append({
            "paper": p.get("title", ""),
            "text": sanitize_dashes(top["text"]),
            "is_new": bool(top.get("is_new")),
        })
    return picks[:top_n]


# ---------------------------------------------------------------------------
# parse the real index.html into the paper data model
# ---------------------------------------------------------------------------

class _CardParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.papers = []
        self.depth = 0
        self.in_card = False
        self.card_depth = 0
        self.in_glance = False
        self.glance_depth = 0
        self.in_h2 = False
        self.in_a = False
        self.in_li = False
        self.in_p = False
        self._reset_card()

    def _reset_card(self):
        self.title_buf = []
        self.href = None
        self.highlights = []
        self.li_buf = []
        self.li_new = False
        self.p_buf = []
        self.paragraphs = []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        cls = a.get("class", "") or ""
        if tag == "div":
            self.depth += 1
            if "paper-card" in cls and not self.in_card:
                self.in_card = True
                self.card_depth = self.depth
                self._reset_card()
            elif self.in_card and "glance" in cls.split():
                self.in_glance = True
                self.glance_depth = self.depth
        elif tag == "h2" and self.in_card:
            self.in_h2 = True
        elif tag == "a" and self.in_h2 and self.href is None:
            self.in_a = True
            self.href = a.get("href")
        elif tag == "li" and self.in_glance:
            self.in_li = True
            self.li_buf = []
            self.li_new = "new" in cls.split()
        elif tag == "p" and self.in_card and not self.in_glance:
            self.in_p = True
            self.p_buf = []

    def handle_data(self, data):
        if self.in_h2:
            self.title_buf.append(data)
        if self.in_li:
            self.li_buf.append(data)
        if self.in_p:
            self.p_buf.append(data)

    def handle_endtag(self, tag):
        if tag == "a" and self.in_a:
            self.in_a = False
        elif tag == "h2" and self.in_h2:
            self.in_h2 = False
        elif tag == "li" and self.in_li:
            self.in_li = False
            text = _clean("".join(self.li_buf))
            if text:
                self.highlights.append({"text": text, "is_new": self.li_new})
        elif tag == "p" and self.in_p:
            self.in_p = False
            text = _clean("".join(self.p_buf))
            if text:
                self.paragraphs.append(text)
        elif tag == "div":
            if self.in_glance and self.depth == self.glance_depth:
                self.in_glance = False
            if self.in_card and self.depth == self.card_depth:
                self._finalize_card()
                self.in_card = False
            self.depth -= 1

    def _finalize_card(self):
        title = _clean("".join(self.title_buf))
        summary = ""
        for para in self.paragraphs:
            if para.lower().startswith("authors:"):
                continue
            if len(para) >= 40:
                summary = para
                break
        # Only cards with real highlights are papers (drops the placeholder).
        if title and self.highlights:
            self.papers.append({
                "title": title,
                "url": self.href or "",
                "summary": summary,
                "highlights": self.highlights,
            })


def _clean(text):
    text = html.unescape(text)
    text = text.replace("\xa0", " ")
    return re.sub(r"\s+", " ", text).strip()


def load_papers(root=ROOT):
    with open(os.path.join(root, "index.html"), "r", encoding="utf-8") as fh:
        parser = _CardParser()
        parser.feed(fh.read())
    return parser.papers


# ---------------------------------------------------------------------------
# render + inject
# ---------------------------------------------------------------------------

def _esc(text):
    return html.escape(text, quote=True)


def render_block(papers, top_n=TOP_N):
    """The full marker-delimited HTML block (At a Glance + per-paper TL;DR)."""
    picks = at_a_glance(papers, top_n=top_n)
    lines = [MARK_START]
    lines.append('<div class="glance-digest" id="at-a-glance">')
    lines.append('<span class="glance-label">At a Glance</span>')
    lines.append('<p class="glance-digest-sub">The top highlight from every '
                 'paper, at a glance.</p>')
    lines.append('<ul class="glance-digest-list">')
    for pick in picks:
        cls = ' class="new"' if pick["is_new"] else ""
        lines.append(
            "<li%s>%s <span class=\"glance-digest-src\">%s</span></li>"
            % (cls, _esc(pick["text"]), _esc(pick["paper"]))
        )
    lines.append("</ul>")
    lines.append('<span class="glance-label">Per-paper TL;DR</span>')
    lines.append('<dl class="tldr-list">')
    for p in papers:
        tldr = derive_tldr(p)
        if not tldr:
            continue
        title = _esc(p["title"])
        url = p.get("url") or ""
        dt = '<a href="%s">%s</a>' % (_esc(url), title) if url else title
        lines.append("<dt>%s</dt><dd>%s</dd>" % (dt, _esc(tldr)))
    lines.append("</dl>")
    lines.append("</div>")
    lines.append(MARK_END)
    return "\n".join(lines)


CSS_BLOCK = CSS_MARK + """
.glance-digest{background:linear-gradient(135deg,rgba(255,165,0,0.07),rgba(123,104,238,0.05));border:1px solid rgba(255,165,0,0.25);border-radius:18px;padding:1.6rem 1.8rem;margin:2rem 0 2.5rem}
.glance-digest .glance-label{font-size:0.7rem;margin-bottom:0.4rem}
.glance-digest-sub{color:rgba(255,255,255,0.5);font-size:0.9rem;margin:0 0 1rem}
.glance-digest-list{margin:0 0 1.4rem;padding:0 0 0 1.1rem;list-style:none}
.glance-digest-list li{position:relative;color:rgba(255,255,255,0.85);font-size:0.92rem;line-height:1.55;margin:0.55rem 0}
.glance-digest-list li::before{content:"\\25B8";color:rgba(255,165,0,0.7);position:absolute;left:-1.1rem}
.glance-digest-list li.new{color:#67e8f9}.glance-digest-list li.new::before{content:"\\2726";color:#67e8f9}
.glance-digest-src{display:block;font-family:'JetBrains Mono',monospace;font-size:0.66rem;letter-spacing:0.04em;color:rgba(255,255,255,0.4);margin-top:0.2rem}
.tldr-list{margin:0.4rem 0 0}
.tldr-list dt{margin-top:0.9rem}
.tldr-list dt a{color:#ffa500;text-decoration:none;font-size:0.95rem;font-weight:600}
.tldr-list dt a:hover{text-decoration:underline}
.tldr-list dd{margin:0.15rem 0 0;color:rgba(255,255,255,0.72);font-size:0.9rem;line-height:1.5}
@media(max-width:768px){.glance-digest{padding:1.3rem}}
"""


def _inject_css(source):
    if CSS_MARK in source:
        repl = CSS_BLOCK.rstrip("\n") + "\n"
        source = re.sub(
            re.escape(CSS_MARK) + r".*?\n(?=</style>)",
            lambda _m: repl,
            source,
            count=1,
            flags=re.DOTALL,
        )
        return source
    # Insert just before the closing </style>.
    return source.replace("</style>", CSS_BLOCK + "</style>", 1)


ANCHOR = '<div id="papers" style="margin-top:3rem;">'


def _inject_block(source, block):
    if MARK_START in source and MARK_END in source:
        return re.sub(
            re.escape(MARK_START) + r".*?" + re.escape(MARK_END),
            lambda _m: block,
            source,
            count=1,
            flags=re.DOTALL,
        )
    if ANCHOR not in source:
        raise SystemExit("ERROR: papers anchor not found in index.html")
    return source.replace(ANCHOR, ANCHOR + "\n\n" + block + "\n", 1)


def build(source, papers):
    source = _inject_css(source)
    source = _inject_block(source, render_block(papers))
    return source


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify index.html is up to date; do not write")
    args = ap.parse_args(argv)

    with open(INDEX, "r", encoding="utf-8") as fh:
        source = fh.read()
    papers = load_papers(ROOT)
    updated = build(source, papers)

    # Guard: the generated content must never carry em/en dashes.
    block = render_block(papers)
    if _EM in block or _EN in block or _EM in CSS_BLOCK or _EN in CSS_BLOCK:
        print("ERROR: generated content contains an em/en dash")
        return 2

    if args.check:
        if updated != source:
            print("DRIFT: index.html At-a-Glance block is out of date.")
            print("       run: python3 scripts/highlights.py")
            return 1
        print("OK: At-a-Glance digest + per-paper TL;DR are in sync "
              f"({len(papers)} papers).")
        return 0

    if updated != source:
        with open(INDEX, "w", encoding="utf-8") as fh:
            fh.write(updated)
        print(f"wrote index.html: {len(papers)} papers, "
              f"{len(at_a_glance(papers))} At-a-Glance highlights.")
    else:
        print("index.html already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
